# Generated by Django 4.1.7 on 2023-04-25 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_reviewrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
