# Generated by Django 4.1.4 on 2023-04-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_description_banner_b_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='b_images',
            field=models.ImageField(upload_to='photos/banners'),
        ),
    ]
