# Generated by Django 4.1.4 on 2023-05-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_upcomingproduct_latestproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingproduct',
            name='category',
        ),
        migrations.DeleteModel(
            name='LatestProduct',
        ),
        migrations.DeleteModel(
            name='UpcomingProduct',
        ),
    ]
