# Generated by Django 4.1.4 on 2023-05-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_user_name_contatcus_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContatcUS',
            new_name='ContactUs',
        ),
    ]
