# Generated by Django 4.1.7 on 2023-03-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pin_code',
            field=models.IntegerField(default=0),
        ),
    ]
